### ISSUE TITLE
debug pass

### ISSUE THREAD

**Issue by riscdanger** [Nowopenstudio/400m#1]
Hey, I dig the site. I ran into a few weird things with the UI, but nothing too important. 

- [x] page flips out if I come back to it's tab in Firefox after a few minutes.
  <img width="662" alt="Screenshot 2024-09-30 at 3 14 38 PM" src="https://github.com/user-attachments/assets/e9138662-af38-4c85-aca8-df8ad658ad3f">

- [x] The Manifesto and Principles tabs share the scroll location. 
  - For example, if I scroll down Manifesto and click Principles, Principles is scrolled down even though I haven't read any of it.

I'll add more as I come across things. :metal:

**Comment by Nowopenstudio** [comment]
- [x] Question counter cuts into the form space at the bottom. Wondering if there’s a way to better deal with that. 
![image](https://github.com/user-attachments/assets/80188bb4-c637-4c2a-9e02-e129a0163acc)

- [x] These were meant to be checked off in order for people to move forward to the questionnaire. Wondering if they should instead just be made to be the first entry in the questionnaire itself.
![image](https://github.com/user-attachments/assets/6f5e901e-4f77-4b52-8eda-b643f08a30eb)

- [x] Another thing I noticed is that there is a lot of space at the bottom of the “Manifesto” and “Principles” pages.
- [ ] ⁨![image](https://github.com/user-attachments/assets/4e1b101f-da2c-4444-9633-7284069e6c5b)
⁩ ⁨These were meant to be checked off in order for people to move forward to the questionnaire. Wondering if they should instead just be made to be the first entry in the questionnaire itself.⁩


- [x] Editing copy on the site. Noticing that the “Heading” formatting on page entries has the text smaller than the main body text.
